# Refer to golangci-lint's example config file for more options and information:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml
version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  concurrency: 4

formatters:
  enable:
    - goimports

linters:
  enable:
    - errcheck
    - gosec
    - govet
    - staticcheck
    - ineffassign
    - unused
    - unparam
    - unconvert
    - tparallel

  settings:
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1016

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
