// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/ming-0x0/yuan/adapter/crypto/bcrypt"
	"github.com/ming-0x0/yuan/adapter/delivery/http/account"
	"github.com/ming-0x0/yuan/adapter/id/sonyflake"
	"github.com/ming-0x0/yuan/adapter/persistence/postgres"
	"github.com/ming-0x0/yuan/internal/account/usecase"
)

// Injectors from wire.go:

func InitializeApp(db *sql.DB) (*account.Handler, error) {
	accountRepository := postgres.NewAccountRepository(db)
	bcrypt := ProvideBcrypt()
	sonyflakeSonyflake, err := sonyflake.New()
	if err != nil {
		return nil, err
	}
	registerUseCase := usecase.NewRegisterUseCase(accountRepository, bcrypt, sonyflakeSonyflake)
	loginUseCase := usecase.NewLoginUseCase(accountRepository, bcrypt)
	handler := account.NewHandler(registerUseCase, loginUseCase)
	return handler, nil
}

// wire.go:

func ProvideBcrypt() *bcrypt.Bcrypt {
	return bcrypt.New(10)
}
