// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	repository "github.com/ming-0x0/yuan/internal/common/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionInterface is a mock of TransactionInterface interface.
type MockTransactionInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionInterfaceMockRecorder
	isgomock struct{}
}

// MockTransactionInterfaceMockRecorder is the mock recorder for MockTransactionInterface.
type MockTransactionInterfaceMockRecorder struct {
	mock *MockTransactionInterface
}

// NewMockTransactionInterface creates a new mock instance.
func NewMockTransactionInterface(ctrl *gomock.Controller) *MockTransactionInterface {
	mock := &MockTransactionInterface{ctrl: ctrl}
	mock.recorder = &MockTransactionInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionInterface) EXPECT() *MockTransactionInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockTransactionInterface) Execute(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockTransactionInterfaceMockRecorder) Execute(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockTransactionInterface)(nil).Execute), ctx, fn)
}

// MockModel is a mock of Model interface.
type MockModel struct {
	ctrl     *gomock.Controller
	recorder *MockModelMockRecorder
	isgomock struct{}
}

// MockModelMockRecorder is the mock recorder for MockModel.
type MockModelMockRecorder struct {
	mock *MockModel
}

// NewMockModel creates a new mock instance.
func NewMockModel(ctrl *gomock.Controller) *MockModel {
	mock := &MockModel{ctrl: ctrl}
	mock.recorder = &MockModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModel) EXPECT() *MockModelMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockModel) Create(createdBy int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Create", createdBy)
}

// Create indicates an expected call of Create.
func (mr *MockModelMockRecorder) Create(createdBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockModel)(nil).Create), createdBy)
}

// Delete mocks base method.
func (m *MockModel) Delete(deletedBy int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", deletedBy)
}

// Delete indicates an expected call of Delete.
func (mr *MockModelMockRecorder) Delete(deletedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockModel)(nil).Delete), deletedBy)
}

// Update mocks base method.
func (m *MockModel) Update(updatedBy int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", updatedBy)
}

// Update indicates an expected call of Update.
func (mr *MockModelMockRecorder) Update(updatedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockModel)(nil).Update), updatedBy)
}

// MockRepository is a mock of Repository interface.
type MockRepository[D any] struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder[D]
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder[D any] struct {
	mock *MockRepository[D]
}

// NewMockRepository creates a new mock instance.
func NewMockRepository[D any](ctrl *gomock.Controller) *MockRepository[D] {
	mock := &MockRepository[D]{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder[D]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository[D]) EXPECT() *MockRepositoryMockRecorder[D] {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository[D]) Create(ctx context.Context, domain *D, createdBy int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, domain, createdBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder[D]) Create(ctx, domain, createdBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository[D])(nil).Create), ctx, domain, createdBy)
}

// Delete mocks base method.
func (m *MockRepository[D]) Delete(ctx context.Context, domain *D, deletedBy int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, domain, deletedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder[D]) Delete(ctx, domain, deletedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository[D])(nil).Delete), ctx, domain, deletedBy)
}

// FindByConditions mocks base method.
func (m *MockRepository[D]) FindByConditions(ctx context.Context, conditions ...repository.Condition) ([]*D, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range conditions {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindByConditions", varargs...)
	ret0, _ := ret[0].([]*D)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByConditions indicates an expected call of FindByConditions.
func (mr *MockRepositoryMockRecorder[D]) FindByConditions(ctx any, conditions ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, conditions...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByConditions", reflect.TypeOf((*MockRepository[D])(nil).FindByConditions), varargs...)
}

// TakeByConditions mocks base method.
func (m *MockRepository[D]) TakeByConditions(ctx context.Context, conditions ...repository.Condition) (*D, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range conditions {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TakeByConditions", varargs...)
	ret0, _ := ret[0].(*D)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TakeByConditions indicates an expected call of TakeByConditions.
func (mr *MockRepositoryMockRecorder[D]) TakeByConditions(ctx any, conditions ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, conditions...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TakeByConditions", reflect.TypeOf((*MockRepository[D])(nil).TakeByConditions), varargs...)
}

// Update mocks base method.
func (m *MockRepository[D]) Update(ctx context.Context, domain *D, updatedBy int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, domain, updatedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder[D]) Update(ctx, domain, updatedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository[D])(nil).Update), ctx, domain, updatedBy)
}

// MockConverter is a mock of Converter interface.
type MockConverter[D any, M any] struct {
	ctrl     *gomock.Controller
	recorder *MockConverterMockRecorder[D, M]
	isgomock struct{}
}

// MockConverterMockRecorder is the mock recorder for MockConverter.
type MockConverterMockRecorder[D any, M any] struct {
	mock *MockConverter[D, M]
}

// NewMockConverter creates a new mock instance.
func NewMockConverter[D any, M any](ctrl *gomock.Controller) *MockConverter[D, M] {
	mock := &MockConverter[D, M]{ctrl: ctrl}
	mock.recorder = &MockConverterMockRecorder[D, M]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConverter[D, M]) EXPECT() *MockConverterMockRecorder[D, M] {
	return m.recorder
}

// ToDomain mocks base method.
func (m *MockConverter[D, M]) ToDomain(arg0 *M) (*D, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToDomain", arg0)
	ret0, _ := ret[0].(*D)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToDomain indicates an expected call of ToDomain.
func (mr *MockConverterMockRecorder[D, M]) ToDomain(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToDomain", reflect.TypeOf((*MockConverter[D, M])(nil).ToDomain), arg0)
}

// ToDomainSlice mocks base method.
func (m *MockConverter[D, M]) ToDomainSlice(arg0 []*M) ([]*D, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToDomainSlice", arg0)
	ret0, _ := ret[0].([]*D)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToDomainSlice indicates an expected call of ToDomainSlice.
func (mr *MockConverterMockRecorder[D, M]) ToDomainSlice(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToDomainSlice", reflect.TypeOf((*MockConverter[D, M])(nil).ToDomainSlice), arg0)
}

// ToModel mocks base method.
func (m *MockConverter[D, M]) ToModel(arg0 *D) (*M, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToModel", arg0)
	ret0, _ := ret[0].(*M)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToModel indicates an expected call of ToModel.
func (mr *MockConverterMockRecorder[D, M]) ToModel(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToModel", reflect.TypeOf((*MockConverter[D, M])(nil).ToModel), arg0)
}

// ToModelSlice mocks base method.
func (m *MockConverter[D, M]) ToModelSlice(arg0 []*D) ([]*M, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToModelSlice", arg0)
	ret0, _ := ret[0].([]*M)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToModelSlice indicates an expected call of ToModelSlice.
func (mr *MockConverterMockRecorder[D, M]) ToModelSlice(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToModelSlice", reflect.TypeOf((*MockConverter[D, M])(nil).ToModelSlice), arg0)
}
